### ISSUE TITLE
Missing guard on import causes non-x86/x64 targets to not compile

### ISSUE THREAD

**Issue by nickbabcock** [oconnor663/blake2b_simd#6]
Just driving by to let you know of a regression for 0.4.0. The following code snippet shows that the second import in the internal benchmark module is unguarded and will cause any non-x86/x64 build to fail:

https://github.com/oconnor663/blake2b_simd/blob/6e7287597aa8b59c1380a516e002f220b2c39cad/src/lib.rs#L917-L919

I recommend using cross inside travis with a target of "mips64-unknown-linux-gnuabi64" to test non-x86/x64 :+1:

**Comment by oconnor663** [comment]
Thank you! Could you point me to a project using cross now, that I could use as a reference?

**Comment by nickbabcock** [comment]
Sure, you can take inspiration from a project of mine (I forgot which project I took this from) [.travis.yml ](https://github.com/nickbabcock/highway-rs/blob/master/.travis.yml) and [corresponding script](https://github.com/nickbabcock/highway-rs/blob/master/ci/script.sh)

Cross does require the use of docker, and I don't know if there will be any interop issues with mac and windows that I see are listed in your blake2b_simd's travis config, so you may have to have the cross tests run only on linux.

**Comment by oconnor663** [comment]
Ok, if https://travis-ci.org/oconnor663/blake2b_simd/builds/446779169 passes then `master` should be good, and then I'll publish v0.4.1. Out of curiosity, how did you run into this break?

**Comment by nickbabcock** [comment]
CI caught it for me: https://github.com/nickbabcock/highway-rs/pull/4 😌

**Comment by oconnor663** [comment]
Just pushed version 0.4.1. Let me know if that doesn't fix CI for you.
